### ISSUE TITLE
Navigation Local Cost map 안나오는 문제 해결

### ISSUE THREAD

**Issue by ChaejinE** [teamlotto/Isaac-Sim-Warehouse#15]
# 목표
- 현재 Navigation 시 rviz에서 Local Cost map이 나오지 않는 상황
   - 주행이 불가
- 사용하고자하는 model : transporter
1. 은지 누나가 셋팅한 정보 확인 후 Navigation Test
   - lidar frame id, topic name, tf tree
2. 위가 정상이면 다시 셋팅해보기

**Comment by ChaejinE** [comment]
# Carter in the Navigation exmaple
![Screenshot from 2021-09-07 17-43-51](https://user-images.githubusercontent.com/69780812/132314089-8c7f3ede-2d2d-48d1-90b7-1981237ee43b.png)
- 일단, Carter는 정상 작동한다.

**Comment by eunji9128** [comment]
https://answers.ros.org/question/191145/problems-with-navigation-stack/
위 사이트 답변을 참조하면 costmap param에서 정의해주는 로봇이나 장애물의 사이즈와 연관이 있어 보임

**Comment by eunji9128** [comment]
![image](https://user-images.githubusercontent.com/80051721/132333687-07a3b409-47a5-4ab7-96d4-45bd58edc339.png)

지금 현재 costmap_common_params.yaml 값

**Comment by ChaejinE** [comment]
# 현재상황
![lidar1_transporter](https://user-images.githubusercontent.com/69780812/132337198-55ef4edd-d56c-40fa-9f87-d992befd8336.gif)
- 라이다 하나 쓰고 Rviz 네비 시, local cost map 확인

**Comment by ChaejinE** [comment]
> ![image](https://user-images.githubusercontent.com/80051721/132333687-07a3b409-47a5-4ab7-96d4-45bd58edc339.png)
> 
> 지금 현재 costmap_common_params.yaml 값

![Screenshot from 2021-09-07 20-40-23](https://user-images.githubusercontent.com/69780812/132338674-b3911057-efad-4628-b9f9-cc2cb0f33294.png)
위 형태로 Costmap 파라미터를 수정했을 시, Rviz에서 local costmap이 나타나지 않았음.
laser_scan 을 여러개 쓰는 형태에 대해 조사 필요

**Comment by eunji9128** [comment]
https://answers.ros.org/question/34095/add-two-laser-for-navigation/
예전 참조 링크

**Comment by ChaejinE** [comment]
기존 트렌스 포터 센서 모델을 사용해서 Ros 토픽 붙여 사용하니 정상작동 및 앞뒤 라이다를 모두 인식하여 이 모델 사용 하기로 결정

**Comment by ChaejinE** [comment]
rviz move base는 scan frame id가 다르더라도 /scan 토픽 이면 알아서 받는 것으로 보인다.
