### ISSUE TITLE
[Turtle Bot] Differential Base 구동 in the LottoWorld01

### ISSUE THREAD

**Issue by ChaejinE** [teamlotto/Isaac-Sim-Warehouse#2]
# 구현 목표
1. LottoWorld01 에서 터틀봇 올리기
2. 터틀봇 텔레옵 진행

**Comment by ChaejinE** [comment]
# 결과
![3](https://user-images.githubusercontent.com/69780812/130405119-18f005af-674b-444e-87e8-af1b05d7f4a0.gif)

**Comment by NamWoo** [comment]
와우~~! 드디어!!! ㅊㅋㅊㅋㅊㅋ

움직일 수 있게 넣은 특징들 잘 정리해두세요~ 그게 핵심~!~~!
