### ISSUE TITLE
LOTTI 및 map 경로 셋팅 중

### ISSUE THREAD

**Issue by ChaejinE** [teamlotto/Isaac-Sim-Warehouse#9]
# 목표
1. Map 경로 셋팅 후 git 관리 원활한지 체크
2. LOTTI  Physics 셋팅

**Comment by ChaejinE** [comment]
# 현재 진행 사항
## 1. git-hub map 경로 셋팅

map, robot 폴더는 은지, 채진 사용
- 경로를 맞춘 체로 은지, 채진이 테스트시 사용한다.
map_bak, robot_bak 폴더는 지연님이 사용
- 경로를 맞춘 체로 버전 업데이트 시 map, robot 폴더에 업데이트 및 백업한다.
## 2. 현재 Lotti Pysics 셋팅
![lotti-create](https://user-images.githubusercontent.com/69780812/131355186-d4f859a5-f845-4d91-84b4-9b6ed62c0895.gif)
- LOTTI 가 선것 같다. Isaac에서 테스트 필요

**Comment by ChaejinE** [comment]
# Isaac-Sim에서 실행
map : LottoWorld03
![lotti-isaac](https://user-images.githubusercontent.com/69780812/131356806-d14f3d20-0ad6-43ce-8e00-45221c6a5c41.gif)
- 음,. 먼가 손을 봐야하는 것 같긴하다.

**Comment by chocoJiyeon** [comment]
뚜껑이 무거워서 가라앉는거면 옷 벗길까요?

**Comment by chocoJiyeon** [comment]
articulation root 값
64
32
50
10000

**Comment by ChaejinE** [comment]
카페트재질이라 바퀴가 가라앉는거같기도,,?

**Comment by ChaejinE** [comment]
# 문제점
![lotti-isaac-wheel](https://user-images.githubusercontent.com/69780812/131435048-ec71349d-2b3f-4c96-a2d9-e23531d84167.gif)
- 바퀴가 카페트에 깔리는 것 아닐 까 ..?

**Comment by ChaejinE** [comment]
![lotti-isaac-wheel](https://user-images.githubusercontent.com/69780812/131438197-60f47dc9-46cd-4aa1-b11b-4be52348d27a.gif)
- 바퀴는 굴러가지만 조인트가 맞지 않는 다는 것을 확인했다.

**Comment by ChaejinE** [comment]
![lotti-move-in-create](https://user-images.githubusercontent.com/69780812/131439327-402d70df-15a8-4833-9471-c60920923e12.gif)
- Joint 를 맞춰주고 create에서 구동

**Comment by ChaejinE** [comment]
scale을 줄였을 때 움직이 않는다.
접촉 면적은 줄었는데, 그라운드 플레인에대한 Friction은 그대로여서 추진력이 구름저항보다 작아 움직이지 않는 것 같다. 
# 문제점
![lotti-notbalance](https://user-images.githubusercontent.com/69780812/131440938-b6593980-14dc-4b70-ab66-20e31906011a.gif)
- 바퀴와 캡슐의 높이가 안맞아서 균형이 맞지 않는다.

**Comment by ChaejinE** [comment]
![create-lotti-frictionmax](https://user-images.githubusercontent.com/69780812/131441766-4dd31345-176b-4084-918b-ea62ac5ad53e.gif)
- scale이 줄어든 대신에에 바퀴의 Friction을 높여줬더니 잘움직였다.

**Comment by ChaejinE** [comment]
# Isaac - sim 에서 테스트
![isaac-test-lotti](https://user-images.githubusercontent.com/69780812/131442378-7cde31ca-c990-44f5-9dd5-da6d1b1d5e09.gif)
- 이상하군..

**Comment by ChaejinE** [comment]
https://meet.google.com/mpi-qcyr-vaf
- 회의 진행

**Comment by ChaejinE** [comment]
# RVIZ - odom이 map과 수직으로 나오는 이유
## Link
![link_test](https://user-images.githubusercontent.com/69780812/131712992-b57c227b-53c5-4ea3-b592-22ef5abbea9b.gif)
- Xform Link는 Z-UP 으로 정상적으로 작동
## Mesh
![case_test](https://user-images.githubusercontent.com/69780812/131713159-7635c181-cee8-4153-81be-57c5f1464c85.gif)
- mesh의 tf는 Y - UP 형태로 작동하고 있음.
